### ISSUE TITLE
Can we extend it to multimodal models?

### ISSUE THREAD

**Issue by RadiantCrystal** [IBM/activation-steering#1]
Hi Team,

Thanks for providing such extensive features in one repo! 

I would like to know can this activation steering code be applicable on multimodal language model such as instructBLIP, PaliGemma, mPLUGowl etc?

**Comment by brucewlee** [comment]
Hi @RadiantCrystal! Thank you for your interest. (I enjoyed your work on Safety Arithmetic)

Applying activation steering to a multimodal language model would be worth a separate research paper for that topic! 

How the library works by wrapping each layer of the model with a LeashLayer and then giving the activation steering parameters to that LeashLayer. To that end, it's important that the library understands the architecture of the model (specifically, the naming schemes of each layer) for it to work. The code that we have is general enough to work on QWEN, LLaMA, OLMo, Mistral, Danube, and etc. and I believe most LLaMA-variants that follow that similar architecture naming scheme would work (https://arxiv.org/pdf/2409.05907).

If you're trying to apply activation steering to the language model portion of the mllm, I think it is possible. 

You can also reach out to brucelws@seas.upenn.edu for any other questions.

(It would be super cool if we could add mllm support in this library)

**Comment by RadiantCrystal** [comment]
Hi @brucewlee,

Thanks for your quick response.

I was wondering if we could use both the vision and langauge part. More like including the image representations as well during the activation steering. I am working on it.

Thanks for sharing your email id. Sure, will reach out if needed. :)

**Comment by RadiantCrystal** [comment]
Hi,

I am also getting 'Segmentation fault (core dumped)' while installing using 'pip install -e activation-steering'. Could you please help?

**Comment by brucewlee** [comment]
Hmm, that's strange. It works fine on my local machine. 

Are you working in a cloud environment? The message often has to do with permission settings.

**Comment by RadiantCrystal** [comment]
I am using local server. I have just downloaded the repo and then executing the 'pip install...' that command. 

Any other workaround?

**Comment by brucewlee** [comment]
What's your Python version? Can you try with an environment with Python version 3.10 or at least 3.9+

**Comment by RadiantCrystal** [comment]
I have python version 3.11.4.

**Comment by brucewlee** [comment]
Okay it just worked for me in Python 3.11.5 environment so it shouldn't be a problem then. Are you using a Conda environment or is your pip command linked to python 3?

**Comment by RadiantCrystal** [comment]
I am using conda environment and updated the pip. Now it is installed. Thanks.

**Comment by brucewlee** [comment]
Great to know!
